### ISSUE TITLE
Starter site: 404 page

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#1536]
Ready to develop.
https://www.figma.com/file/vCgPY3JxjHO6e838AYGyjo/Starter-Website?type=design&node-id=42%3A1552&mode=design&t=ENGd3STmKB9wfqnD-1

**Comment by kkoryaka** [comment]
@extinah check the newest zip

**Comment by lakey8085CDT** [comment]
@kkoryaka and @extinah...I know it's a 404 page _**and**_ I've been noticing more and more sites with 404 pages that are kinda whimsical in nature. Is that acceptable round these parts? 

[404 concepts/ideas](https://www.smashingmagazine.com/2018/11/the-101-course-on-crafting-404-pages/)

Otherwise, this page is solid.

**Comment by lakey8085CDT** [comment]
@kkoryaka and @extinah, I'm probably splitting doll-hairs at this point, but we could shorten the language, in some places.

'To find what you need, you can:' OR 'Find what you need, by:' 

we'd have to 'ing' the bullets below, though.
- Brows(ing) our homepage
- Double checking that link
- Us(ing) our search or the site map
- Checking out these popular links:

We could also get creative and make it artsy-fartsy.  ; - )

**Comment by extinah** [comment]
@lakey8085CDT As discussed, let's add language on the UI kit that states departments can update the 404 page based on their department tone. 
@kkoryaka  Approved. Thanks!
