### ISSUE TITLE
Android: Mobile: Side navigation closes when Search box gets focus

### ISSUE THREAD

**Issue by CalEPA-Jansson** [Office-of-Digital-Services/California-State-Web-Template-Website#1650]
To reproduce:
- Go to https://template.webstandards.ca.gov on an Android device
- Open the side navigation menu
- Tap on the "Search" text box

I believe when the keyboard is rendered, it resizes the browser viewport and triggers the resize listener functions (which closes the side navigation). Note this behavior does not appear to exist on iPhone.

**Comment by kkoryaka** [comment]
@CalEPA-Jansson when you talking about side navigation menu do you mean actual side navigation component or main navigation menu? BTW we have made some accessibility improvements to the mobile menu in our [latest v6.3.1 release](https://github.com/Office-of-Digital-Services/California-State-Web-Template-HTML/releases), check if your issue is still present.

**Comment by kkoryaka** [comment]
@CalEPA-Jansson this issue is now fixed in v6.3.2 release.
