### ISSUE TITLE
Download and setup

### ISSUE THREAD

**Issue by extinah** [Office-of-Digital-Services/California-State-Web-Template-Website#721]
Write content, design, and develop this new page. Created out of the getting started content.

doc: https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit?usp=share_link
figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official

@hamiltonryan when you're done can you move the figma board to the getting started area? Appreciate it. Thanks!

**Comment by extinah** [comment]
Hi @kkoryaka 
Ready for dev. It's a long one. Hope you (or whoever) has fun :)

Content: https://docs.google.com/document/d/1A--CplY-8qepW4dG_jG0Bdg-eiDgqZ5RQgt7lD8jVPo/edit?usp=share_link
Figma: https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=806%3A10772

**Comment by Greg-Watanabe** [comment]
@extinah @sharon-rabang 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html
I changed the code snippet containers to <pre> and <code> tags as requested by Konstantin.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks for making this page design work! It's looking good with some minor changes to make:

- Common V6 cards: Use Public Sans, Bold for the sentences
-  Template implementation roadmap, headings: Change the font style from <strong> to Public Sans, Bold
-  Template implementation roadmap, #4: Add a link to the [GitHub Repository](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/).
- Using Eleventy, Step 2: Change the buttons' and labels' colors to #046B99
- Documentation for Eleventy, Includes: Change the button and label colors to #046B99

@extinah @hamiltonryan Please let me know if I missed anything, thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! FYI - The UX review is reassigned to @hamiltonryan for review and feedback. There were recent content changes made to the google doc that we are currently adding to Figma. We'll let you know when our list of changes are ready for dev.

**Comment by hamiltonryan** [comment]
@Greg-Watanabe Thanks for all the work on this one! Here are the changes to Figma based on the updated Google Doc. 

- Get Started should now be linked in the Breadcrumb
- The boxes of common links should be the same width (flex about 30%)
![image](https://user-images.githubusercontent.com/101579462/199779190-fc80996d-384b-4f62-96d6-9c6362891d79.png)
- The sentence "Here are the steps to follow when implementing the V6 State Web Template." is now after the common links section.
- The heading for Step 3 of the Template implementation was updated to "Understand the differences in the code"
-  The image of Step 4 of the Template implementation was removed.
- The was a new step added into Step 5 (pushing current to 6, and so on)
- In the new Steps 6 of the Template implementation, "template" was removed from the heading 
![image](https://user-images.githubusercontent.com/101579462/199781136-6b6220b4-1259-43e9-bbee-ac5dadde1663.png)
- The sentence in Step 2 of Using Elevety was updated. to just have an "s" at the very end. So it should be "codes" instead of "code"
- The sentence between Using Eleventy and Step1 has now been removed
![image](https://user-images.githubusercontent.com/101579462/199784202-f67c4e81-9ea7-41b9-b198-aba61dff5189.png)

- The sentence in #2 of Step 4 of Using Elevety has been updated. It should read: "Use this command to build and generate your website's pages, css and js files." ("your" was added in before "website's pages")
- The Output section should now read "All web content is generated into the /_site/ folder, which is the website's final output folder." ( "the" was added before "website's final output")

**Comment by extinah** [comment]
@Greg-Watanabe ready for your updates. Thanks.

**Comment by Greg-Watanabe** [comment]
@extinah  @hamiltonryan 
This is done
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/download-and-setup.html
