### ISSUE TITLE
Search functionality improvements for beta

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#822]
- [x] Need to re-index site
- [x] add correct search ID 
- [ ] create search collection
- [x] Requested manual indexing on key pages

Work with Linda Tracy

**Comment by kkoryaka** [comment]
@Leeendahh this is for https://beta.template.webstandards.ca.gov/ would you be able to help?

**Comment by Leeendahh** [comment]
@kkoryaka Absolutely. I'll get started on creating a Search Engine account for https://beta.template.webstandards.ca.gov/. It is currently lumped in with https://template.webstandards.ca.gov/.

**Comment by Leeendahh** [comment]
@kkoryaka I submitted the sitemap for re-indexing. This may take a few days to a few weeks. 

Here is the Search Engine ID for https://beta.template.webstandards.ca.gov/: 05e92f21f387b4800

Ads will appear in Search Results for now. I will submit a request to have the search engine registered as a Government Edition of Programmable Search Engine so I can turn ads off in search results. This may take a day or two get approved by Google.

**Comment by Leeendahh** [comment]
Submitted Government Edition request. I'll update once it's been approved and Ads are turned off.

**Comment by Leeendahh** [comment]
Update: 
I confirmed through Google Search Console that pages are live and that Google detects the pages. I've submitted 8 manual indexing requests for the following pages:
- https://beta.template.webstandards.ca.gov/
- https://beta.template.webstandards.ca.gov/template-updates.html
- https://beta.template.webstandards.ca.gov/get-started.html
- https://beta.template.webstandards.ca.gov/structure.html
- https://beta.template.webstandards.ca.gov/visual-design/color.html
- https://beta.template.webstandards.ca.gov/visual-design/icons.html
- https://beta.template.webstandards.ca.gov/visual-design/typography.html
- https://beta.template.webstandards.ca.gov/components.html

I'm hoping the manual index request helps index the site a little quicker since it's new. 

Per Google, indexing a new site after submitting a sitemap can take anywhere from 1-2 days to even a few weeks. Let's hope time is on our side and it's sometime within the next week. It's in Google's hands/control now.

I'm not sure how proactive we want to be - but it may be worth adding an on page alert on the search page to let users know our site is new and that it may take up to a month for search results to populate for the site. It's in Google's hands/control now.

**Comment by extinah** [comment]
@kkoryaka When i select a link, it opens in a new tab. can that be fixed? doesn't seem to be related to the google console.
https://beta.template.webstandards.ca.gov/serp.html?q=

**Comment by extinah** [comment]
@yesenia-gtz  please clarify "google search collection". Been working with Linda a bit. Thanks!

**Comment by yesenia-gtz** [comment]
@extinah @Leeendahh I was thinking we could benefit from a search collection per the following context. We may be able to help people access specific content.

"A collection lets your users search over a specific part of the index. For example, you may want to create a products collection or a human_resources collection that supports searches that are only within the products or human resources part of your index. The [Page Layout Helper](https://www.google.com/support/enterprise/static/gsa/docs/admin/74/admin_console_help/serve_output_layout.html) lets you automatically modify the search page to include a menu for [search by collection](https://www.google.com/support/enterprise/static/gsa/docs/admin/74/admin_console_help/serve_output_layout.html#search_box)."

Source: https://www.google.com/support/enterprise/static/gsa/docs/admin/74/admin_console_help/crawl_collections.html

If not needed we can skip for production release.
cc @artuoma
